// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

using System.Linq.Expressions;
using System.Reflection;
using Microsoft.AspNetCore.Components.QuickGrid.Infrastructure;
using Microsoft.AspNetCore.Components.Rendering;

namespace Microsoft.AspNetCore.Components.QuickGrid.Tests;

public class PropertyColumnTest
{
    private class TestEntity
    {
        public int Id { get; set; }
        public string Name { get; set; } = string.Empty;
        public DateTime CreatedDate { get; set; }
        public decimal? Salary { get; set; }
        public TestChild Child { get; set; } = new();
    }

    private class TestChild
    {
        public string ChildName { get; set; } = string.Empty;
    }

    [Fact]
    public void PropertyColumn_SortBy_IsSetFromPropertyExpression()
    {
        // Arrange
        var column = new PropertyColumn<TestEntity, string>();
        Expression<Func<TestEntity, string>> propertyExpr = x => x.Name;

        // Act - set Property through reflection to simulate component lifecycle
        var propertyInfo = typeof(PropertyColumn<TestEntity, string>).GetProperty("Property");
        propertyInfo?.SetValue(column, propertyExpr);

        // Use reflection to call protected OnParametersSet
        var onParamsMethod = typeof(PropertyColumn<TestEntity, string>).GetMethod("OnParametersSet", BindingFlags.NonPublic | BindingFlags.Instance);
        onParamsMethod?.Invoke(column, null);

        // Assert - SortBy should be automatically created from the property
        Assert.NotNull(column.SortBy);
    }

    [Fact]
    public void PropertyColumn_Title_AutoGeneratedFromPropertyName()
    {
        // Arrange
        var column = new PropertyColumn<TestEntity, string>();
        Expression<Func<TestEntity, string>> propertyExpr = x => x.Name;

        // Act
        var propertyInfo = typeof(PropertyColumn<TestEntity, string>).GetProperty("Property");
        propertyInfo?.SetValue(column, propertyExpr);

        var onParamsMethod = typeof(PropertyColumn<TestEntity, string>).GetMethod("OnParametersSet", BindingFlags.NonPublic | BindingFlags.Instance);
        onParamsMethod?.Invoke(column, null);

        // Assert - Title should be auto-generated from property name
        Assert.Equal("Name", column.Title);
    }

    [Fact]
    public void PropertyColumn_CustomTitle_NotOverwritten()
    {
        // Arrange
        var column = new PropertyColumn<TestEntity, string>();
        Expression<Func<TestEntity, string>> propertyExpr = x => x.Name;

        // Act
        column.Title = "Custom Title";
        var propertyInfo = typeof(PropertyColumn<TestEntity, string>).GetProperty("Property");
        propertyInfo?.SetValue(column, propertyExpr);

        var onParamsMethod = typeof(PropertyColumn<TestEntity, string>).GetMethod("OnParametersSet", BindingFlags.NonPublic | BindingFlags.Instance);
        onParamsMethod?.Invoke(column, null);

        // Assert - Custom title should not be overwritten
        Assert.Equal("Custom Title", column.Title);
    }

    [Fact]
    public void PropertyColumn_Format_AcceptedForIFormattableType()
    {
        // Arrange
        var column = new PropertyColumn<TestEntity, int>();
        Expression<Func<TestEntity, int>> propertyExpr = x => x.Id;

        // Act
        var propertyInfo = typeof(PropertyColumn<TestEntity, int>).GetProperty("Property");
        propertyInfo?.SetValue(column, propertyExpr);
        column.Format = "D4";

        var onParamsMethod = typeof(PropertyColumn<TestEntity, int>).GetMethod("OnParametersSet", BindingFlags.NonPublic | BindingFlags.Instance);
        onParamsMethod?.Invoke(column, null);

        // Assert - no exception means success
        Assert.Equal("D4", column.Format);
    }

    [Fact]
    public void PropertyColumn_FormatNonIFormattable_ThrowsInvalidOperation()
    {
        // Arrange
        var column = new PropertyColumn<TestEntity, TestEntity>();
        Expression<Func<TestEntity, TestEntity>> propertyExpr = x => x;

        // Act
        var propertyInfo = typeof(PropertyColumn<TestEntity, TestEntity>).GetProperty("Property");
        propertyInfo?.SetValue(column, propertyExpr);
        column.Format = "someformat";

        var onParamsMethod = typeof(PropertyColumn<TestEntity, TestEntity>).GetMethod("OnParametersSet", BindingFlags.NonPublic | BindingFlags.Instance);

        // Assert - reflection wraps exception, so we check inner exception
        var exception = Assert.Throws<TargetInvocationException>(() => onParamsMethod?.Invoke(column, null));
        Assert.IsType<InvalidOperationException>(exception.InnerException);
        Assert.Contains("does not implement", exception.InnerException!.Message);
    }

    [Fact]
    public void PropertyColumn_SortBy_SetThrowsNotSupportedException()
    {
        // Arrange
        var column = new PropertyColumn<TestEntity, string>();
        Expression<Func<TestEntity, string>> propertyExpr = x => x.Name;

        var propertyInfo = typeof(PropertyColumn<TestEntity, string>).GetProperty("Property");
        propertyInfo?.SetValue(column, propertyExpr);

        var onParamsMethod = typeof(PropertyColumn<TestEntity, string>).GetMethod("OnParametersSet", BindingFlags.NonPublic | BindingFlags.Instance);
        onParamsMethod?.Invoke(column, null);

        // Act & Assert - trying to set SortBy directly should throw NotSupportedException
        Assert.Throws<NotSupportedException>(() => column.SortBy = null);
    }

    [Fact]
    public void PropertyColumn_NullableProperty_Works()
    {
        // Arrange
        var column = new PropertyColumn<TestEntity, decimal?>();
        Expression<Func<TestEntity, decimal?>> propertyExpr = x => x.Salary;

        // Act
        var propertyInfo = typeof(PropertyColumn<TestEntity, decimal?>).GetProperty("Property");
        propertyInfo?.SetValue(column, propertyExpr);

        var onParamsMethod = typeof(PropertyColumn<TestEntity, decimal?>).GetMethod("OnParametersSet", BindingFlags.NonPublic | BindingFlags.Instance);
        onParamsMethod?.Invoke(column, null);

        // Assert
        Assert.Equal("Salary", column.Title);
        Assert.NotNull(column.SortBy);
    }

    [Fact]
    public void PropertyColumn_DateTimeFormat_Works()
    {
        // Arrange
        var column = new PropertyColumn<TestEntity, DateTime>();
        Expression<Func<TestEntity, DateTime>> propertyExpr = x => x.CreatedDate;

        // Act
        var propertyInfo = typeof(PropertyColumn<TestEntity, DateTime>).GetProperty("Property");
        propertyInfo?.SetValue(column, propertyExpr);
        column.Format = "yyyy-MM-dd";

        var onParamsMethod = typeof(PropertyColumn<TestEntity, DateTime>).GetMethod("OnParametersSet", BindingFlags.NonPublic | BindingFlags.Instance);
        onParamsMethod?.Invoke(column, null);

        // Assert - DateTime implements IFormattable
        Assert.Equal("yyyy-MM-dd", column.Format);
    }

    [Fact]
    public void PropertyColumn_NonNullableIntProperty_Works()
    {
        // Arrange
        var column = new PropertyColumn<TestEntity, int>();
        Expression<Func<TestEntity, int>> propertyExpr = x => x.Id;

        // Act
        var propertyInfo = typeof(PropertyColumn<TestEntity, int>).GetProperty("Property");
        propertyInfo?.SetValue(column, propertyExpr);

        var onParamsMethod = typeof(PropertyColumn<TestEntity, int>).GetMethod("OnParametersSet", BindingFlags.NonPublic | BindingFlags.Instance);
        onParamsMethod?.Invoke(column, null);

        // Assert - non-nullable int should work
        Assert.Equal("Id", column.Title);
        Assert.NotNull(column.SortBy);
    }

    [Fact]
    public void PropertyColumn_Class_Property()
    {
        // Arrange
        var column = new PropertyColumn<TestEntity, string>();
        Expression<Func<TestEntity, string>> propertyExpr = x => x.Name;

        // Act
        var propertyInfo = typeof(PropertyColumn<TestEntity, string>).GetProperty("Property");
        propertyInfo?.SetValue(column, propertyExpr);
        column.Class = "custom-class";

        var onParamsMethod = typeof(PropertyColumn<TestEntity, string>).GetMethod("OnParametersSet", BindingFlags.NonPublic | BindingFlags.Instance);
        onParamsMethod?.Invoke(column, null);

        // Assert
        Assert.Equal("custom-class", column.Class);
    }

    [Fact]
    public void PropertyColumn_Align_Property()
    {
        // Arrange
        var column = new PropertyColumn<TestEntity, string>();
        Expression<Func<TestEntity, string>> propertyExpr = x => x.Name;

        // Act
        var propertyInfo = typeof(PropertyColumn<TestEntity, string>).GetProperty("Property");
        propertyInfo?.SetValue(column, propertyExpr);
        column.Align = Align.Center;

        var onParamsMethod = typeof(PropertyColumn<TestEntity, string>).GetMethod("OnParametersSet", BindingFlags.NonPublic | BindingFlags.Instance);
        onParamsMethod?.Invoke(column, null);

        // Assert
        Assert.Equal(Align.Center, column.Align);
    }

    [Fact]
    public void PropertyColumn_NestedPropertyExpression_Works()
    {
        // Arrange
        var column = new PropertyColumn<TestEntity, string>();
        Expression<Func<TestEntity, string>> propertyExpr = x => x.Child.ChildName;

        // Act
        var propertyInfo = typeof(PropertyColumn<TestEntity, string>).GetProperty("Property");
        propertyInfo?.SetValue(column, propertyExpr);

        var onParamsMethod = typeof(PropertyColumn<TestEntity, string>).GetMethod("OnParametersSet", BindingFlags.NonPublic | BindingFlags.Instance);
        onParamsMethod?.Invoke(column, null);

        // Assert - Title should be the name of the last property in the nested path
        Assert.Equal("ChildName", column.Title);
    }

    [Fact]
    public void PropertyColumn_DefaultSort_IsNotSortable()
    {
        // Arrange
        var column = new PropertyColumn<TestEntity, string>();
        Expression<Func<TestEntity, string>> propertyExpr = x => x.Name;

        // Act
        var propertyInfo = typeof(PropertyColumn<TestEntity, string>).GetProperty("Property");
        propertyInfo?.SetValue(column, propertyExpr);

        var onParamsMethod = typeof(PropertyColumn<TestEntity, string>).GetMethod("OnParametersSet", BindingFlags.NonPublic | BindingFlags.Instance);
        onParamsMethod?.Invoke(column, null);

        var isSortableByDefaultMethod = typeof(PropertyColumn<TestEntity, string>).BaseType.GetMethod("IsSortableByDefault", BindingFlags.NonPublic | BindingFlags.Instance);
        var isSortableByDefault = isSortableByDefaultMethod?.Invoke(column, null);
        Assert.False((bool)isSortableByDefault!); // Base class returns false
    }
}